# Reading and Writing Data (CSV, Excel, JSON, SQL)

-- In real-world data analysis, you’ll usually work with external files — like CSVs, Excel sheets, JSON files, and even SQL databases.

-- Pandas makes it super easy to read and write these formats. Let’s go through them one by one.

In [1]:
import pandas as pd

# ✅ 1. Reading Data

In [2]:
df = pd.read_csv("C:\Data Analytics\Python\Pandas\insurance.csv")
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

# 📂 Reading an Excel file

-- ⚠️ Note: You need to install openpyxl
-- pip install openpyxl

In [3]:
df2 = pd.read_excel("C:\Data Analytics\EXCEL ADVANCE\PROJECTS\Project -1 Hiring Process\Statistics.xlsx")
df2.head()

,application_id,Interview Taken on,Status,event_name,Department,Post Name,Offered Salary
0,383422,2014-05-01 11:40:49,Hired,Male,Service Department,c8,56553.0
1,907518,2014-05-06 08:08:32,Hired,Female,Service Department,c5,22075.0
2,176719,2014-05-06 08:08:54,Rejected,Male,Service Department,c5,70069.0
3,429799,2014-05-02 16:28:59,Rejected,Female,Operations Department,i4,3207.0
4,253651,2014-05-02 16:32:26,Hired,Male,Operations Department,i4,29668.0

# Reading a Json File

In [4]:
df3 = pd.read_json("C:\Users\Rajeev\Downloads\example_1.json")
df3.head()

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1568978036.py, line 1)

In [8]:
df3 =  pd.read_json(r"C:\Users\Rajeev\Downloads\example_2.json")
df3.head()

                                                    quiz
sport  {'q1': {'question': 'Which one is correct team...
maths  {'q1': {'question': '5 + 7 = ?', 'options': ['...